-- MySQL Script generated by MySQL Workbench
-- Fri May 29 14:30:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bibliothek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bibliothek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bibliothek` DEFAULT CHARACTER SET utf8 ;
USE `Bibliothek` ;

-- -----------------------------------------------------
-- Table `Bibliothek`.`Medium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Medium` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EAN` INT NOT NULL,
  `Titel` VARCHAR(45) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `Altersfreigabe` INT NOT NULL,
  `Standordcode` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Buch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Buch` (
  `ISBN` CHAR NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `Medium_ID` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Buch_Medium_idx` (`Medium_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Buch_Medium`
    FOREIGN KEY (`Medium_ID`)
    REFERENCES `Bibliothek`.`Medium` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`DVD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`DVD` (
  `Produktionsstudio` VARCHAR(45) NOT NULL,
  `Medium_ID` INT NOT NULL,
  INDEX `fk_DVD_Medium1_idx` (`Medium_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DVD_Medium1`
    FOREIGN KEY (`Medium_ID`)
    REFERENCES `Bibliothek`.`Medium` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Audio-CD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Audio-CD` (
  `Interpret` INT NOT NULL,
  `Medium_ID` INT NOT NULL,
  INDEX `fk_Audio-CD_Medium1_idx` (`Medium_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Audio-CD_Medium1`
    FOREIGN KEY (`Medium_ID`)
    REFERENCES `Bibliothek`.`Medium` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Game` (
  `Anforderungen` TEXT NOT NULL,
  `Entwicklerstudio` VARCHAR(45) NOT NULL,
  `Medium_ID` INT NOT NULL,
  INDEX `fk_Game_Medium1_idx` (`Medium_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Medium1`
    FOREIGN KEY (`Medium_ID`)
    REFERENCES `Bibliothek`.`Medium` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Kunde` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nachname` VARCHAR(45) NOT NULL,
  `Vorname` VARCHAR(45) NOT NULL,
  `Geburtsdatum` DATE NOT NULL,
  `EMail` VARCHAR(45) NOT NULL,
  `Passwort` CHAR(45) NOT NULL,
  `Kundennummer` INT NOT NULL DEFAULT 00001,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Kundenkarte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Kundenkarte` (
  `Kartennummer` INT NOT NULL DEFAULT 0001,
  `Ausstelldatum` DATE NOT NULL,
  `Ablaufdatum` DATE NOT NULL,
  `Kunde_ID` INT NOT NULL,
  PRIMARY KEY (`Kartennummer`),
  INDEX `fk_Kundenkarte_Kunde1_idx` (`Kunde_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Kundenkarte_Kunde1`
    FOREIGN KEY (`Kunde_ID`)
    REFERENCES `Bibliothek`.`Kunde` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Ausleihen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Ausleihen` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Kunde` INT NOT NULL,
  `Medium` INT NOT NULL,
  `Datum` DATE NOT NULL,
  INDEX `fk_Kunde_has_Medium_Medium1_idx` (`Medium` ASC) VISIBLE,
  INDEX `fk_Kunde_has_Medium_Kunde1_idx` (`Kunde` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Kunde_has_Medium_Kunde1`
    FOREIGN KEY (`Kunde`)
    REFERENCES `Bibliothek`.`Kunde` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kunde_has_Medium_Medium1`
    FOREIGN KEY (`Medium`)
    REFERENCES `Bibliothek`.`Medium` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliothek`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliothek`.`Adresse` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Strasse` VARCHAR(45) NOT NULL,
  `Ort` VARCHAR(45) NOT NULL,
  `PLZ` VARCHAR(4) NOT NULL,
  `Kunde_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Adresse_Kunde1_idx` (`Kunde_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Adresse_Kunde1`
    FOREIGN KEY (`Kunde_ID`)
    REFERENCES `Bibliothek`.`Kunde` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
